### ISSUE TITLE
I can’t Dectect lame on yellowshoes

### ISSUE THREAD

**Issue by elmogosogo09usa** [evuraan/yellowShoes#12]
I tried everything on windows to get lame to work however I didn’t have a solution to the problem I have  iOS devices and my server that runs use windows

**Comment by evuraan** [comment]
Try placing `lame.exe` into your `%PATH%` before launching `yellowShoes`. 

Or

```powershell
$env:Path += ";C:\FolderWhereLameLives"
```


Closing, not a bug of my creation.

**Comment by anmathew** [comment]
hi @elmogosogo09usa , can you please try with[ this test build ](https://github.com/evuraan/yellowShoes/issues/14#issuecomment-1840104977)and see if that works?

**Comment by elmogosogo09usa** [comment]
Also I should add different audio formats
