### ISSUE TITLE
Can't Find NRSC5 Binary

### ISSUE THREAD

**Issue by ferrellsl** [evuraan/yellowShoes#14]
When running the yellowshoes-win-amd64 binary on Windows 11 I get the following error even if the nrsc5 exe and DLL are in the same folder with yellowshoes or if they're in the path:

yellowShoes Ver 6.01b.1682825162 Copyright (C) Evuraan <evuraan@gmail.com>
This program comes with ABSOLUTELY NO WARRANTY.
Using temp dir: C:\Users\steve\AppData\Local\Temp, port: 8113
Error 11.1 - Could not locate nrsc5 binary

yellowShoes Ver 5.0h.1660853114 works without issue

**Comment by evuraan** [comment]
Please show o/p of 

```powershell
PS:> where.exe nrsc nrsc5.exe
```

**Comment by ferrellsl** [comment]
> Please show o/p of
> 
> ```powershell
> PS:> where.exe nrsc nrsc5.exe
> ```
<img width="415" alt="image" src="https://github.com/evuraan/yellowShoes/assets/5926287/3037d5f7-71d5-493c-b712-6e68a7ab036c">

**Comment by evuraan** [comment]
While it finds in your local folder, it does not mean your folder is in your PATH. 
```powershell
($env:PATH -split ";" -ccontains 'D:\yellowshoes\') 
```
Or try this:
```powershell
PS:> $env:Path += ";D:\yellowshoes\"
PS:> yellowshoes.exe 
```

**Comment by ferrellsl** [comment]
As I said in my first post, it doesn't matter if the nrsc5 binary is in my path or in the same folder as yellowshoes.  It isn't finding the nrsc5 binary.  The binary is also located in C:\windows\system32  which IS in my path.  See below:

<img width="652" alt="image" src="https://github.com/evuraan/yellowShoes/assets/5926287/04e434a5-1934-4d2e-b2fb-32f3dec7dd9e">

<img width="550" alt="image" src="https://github.com/evuraan/yellowShoes/assets/5926287/a5bc75be-1d3e-4cce-8808-62b1e93e2c75">


Version 5 of yellowshoes runs just fine from this very same folder, but not version 6.

**Comment by evuraan** [comment]
if you copy yellowshoes.exe as nrsc5 and try as below, does it stick longer? 

![image](https://github.com/evuraan/yellowShoes/assets/39205936/cafc2554-9bba-42d8-979a-7966a35a25b9)

**Comment by ferrellsl** [comment]
Still no joy.

<img width="553" alt="image" src="https://github.com/evuraan/yellowShoes/assets/5926287/e5589a65-8846-4f04-985e-bfb70e37c5a9">

<img width="848" alt="image" src="https://github.com/evuraan/yellowShoes/assets/5926287/c63c1a42-e5b8-43cb-822c-f5691fefe853">

**Comment by evuraan** [comment]
oy! quite a stumper, this one! 

can you please zip this folder up and attach here? or email to me at gmail com?

**Comment by ferrellsl** [comment]
Here you go.
[yellowshoes-glitch.zip](https://github.com/evuraan/yellowShoes/files/13555051/yellowshoes-glitch.zip)

**Comment by evuraan** [comment]
Thanks, that very zip file works for me!

![image](https://github.com/evuraan/yellowShoes/assets/39205936/f22b09db-19a2-44ac-93ed-da046abdf189)

Can you remove the `System32\nrsc5.exe` and try with one local copy?

**Comment by ferrellsl** [comment]
Dang, that's weird.  Let me see what happens on another system.

**Comment by evuraan** [comment]
The closest I could repro this was inside a Sandbox, Win10, Admin powershell window: 

![image](https://github.com/evuraan/yellowShoes/assets/39205936/424cea74-1824-4194-8f34-0f99e6d1af63)

**Comment by ferrellsl** [comment]
Well, I'm stumped.  I get the same error on one of my other systems.

**Comment by ferrellsl** [comment]
OK, looks like it's related to admin privileges.  When I run Powershell as an admin, I get success!  Thanks for your patience.

**Comment by evuraan** [comment]
oh great, lmk what you find! 

Instead of hinging on admin privs, we can try adding an arg to specify the full path to `nsrc5.exe` and see if that helps.

**Comment by ferrellsl** [comment]
Yes, it's definitely related to admin vs a non-admin Powershell.  When I run an admin Powershell and add the yellowshoes folder to the path everything works as expected on both of my systems.  An easier option might be to just create a .ps1 script and run that as an admin.

**Comment by ferrellsl** [comment]
Here's a solution that works for me.  I created a yellowshoes.ps1 file with the following contents in my yellowshoes folder:

d:
cd \yellowshoes
$env:path += ";d:\yellowshoes"
.\yellowShoes-win-amd64.exe -enableAlbumArt


Next, I created a short-cut file in the same folder.  The properties of the short-cut are:

C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -F d:\yellowshoes\yellowshoes.ps1

In order to just run it by double-clicking the short-cut, right-click on the short-cut file and select Properties->Advanced->Run as Administrator

**Comment by evuraan** [comment]
[6.02testBuild.1660493379.zip](https://github.com/evuraan/yellowShoes/files/13555866/6.02testBuild.1660493379.zip)

Can you please try (as non admin) with the test build in the attached zip file? Use the `-nrscPath` to specify the location of your `nrsc5` binary. 

```bash
$ sha256sum 6.02testBuild.1660493379.zip yellowShoes.exe 
8526d1bae15d8b940d4f57aab052e004bf70caecdc2c9569633bc3e576211eb2  6.02testBuild.1660493379.zip
cba22a3288b5e601427e59797216f41f67e66cb88db9f55936f028502452b055  yellowShoes.exe

$ unzip -l 6.02testBuild.1660493379.zip 
Archive:  6.02testBuild.1660493379.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 10840576  2023-12-04 21:57   yellowShoes.exe
---------                     -------
 10840576                     1 file

```


![image](https://github.com/evuraan/yellowShoes/assets/39205936/f2f02dd2-353d-4d05-baa0-162f75009135)

**Comment by ferrellsl** [comment]
Yes, that works!

**Comment by evuraan** [comment]
I wonder if #12 if were the manifestation of a similar issue, but with `lame` instead of `nrsc5`. Perhaps adding a `-lamePath` arg will be prudent!

**Comment by ferrellsl** [comment]
I bet you're on to something.

**Comment by anmathew** [comment]
[6.03testBuild.1701758383.zip](https://github.com/evuraan/yellowShoes/files/13556156/6.03testBuild.1701758383.zip)

Updated _test_ build with `-lamePath` option added:

```bash
Usage of ./yellowShoes:
  -enableAlbumArt
    	enable album art
  -lamePath string
    	Optional: fullpath to lame binary
  -nrscPath string
    	Optional: fullpath to nrsc5 binary
  -port int
    	port to use (default 8113)
  -tempFolder string
    	temp folder with write access to use (default "/tmp")
  -v	print version information and exit
```

```bash
$ sha256sum 6.03testBuild.1701758383.zip yellowShoes.exe  
0d8d9a1f5d63a957e2ff3b368ccd4d32fa4339f95b2f10d2521bc6c8ba859801  6.03testBuild.1701758383.zip
891a8a4b77aec1bbcbd457f25b4301dace5147181b4e8c6d14715266f1224b0f  yellowShoes.exe

$ unzip -l 6.03testBuild.1701758383.zip 
Archive:  6.03testBuild.1701758383.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 10840064  2023-12-04 22:41   yellowShoes.exe
---------                     -------
 10840064                     1 file

```

**Comment by ferrellsl** [comment]
I haven't tried the lame option yet.  I'm running into a problem with your earlier test build.  It runs, but when I attempt to tune to a station in my browser, it times out.  The shell is showing this:

<img width="650" alt="image" src="https://github.com/evuraan/yellowShoes/assets/5926287/70ea2ad5-d5ac-41e3-bf45-bbea1c49dcfe">

**Comment by anmathew** [comment]
need absolute path to the exe. try with `-nrscPath d:\yellowshoes\nrsc.exe -enableAlbumArt ...`

**Comment by ferrellsl** [comment]
LOL!  Yes, that was it.  Thanks again for your patience.

**Comment by ferrellsl** [comment]
Just tried to transcode via lame. Pretty sure I'm doing something wrong as it fails.  Here's what my shell says:

<img width="849" alt="image" src="https://github.com/evuraan/yellowShoes/assets/5926287/a7d18710-3a3f-4bf0-b27d-85fc77a41980">


Browser spits out this log:

yellowShoes
nrsc5 radio player (HD FM Radio)
Error: Playback failed on 94.5 MHz.
Here's your full log:

Exact sample rate is: 1488375.071248 Hz
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
00:03:25 Synchronized
00:03:25 Audio program 0: public, type: None, sound experience 0
00:03:25 Audio program 1: public, type: None, sound experience 0
00:03:25 Audio program 1: public, type: None, sound experience 0
00:03:25 Slogan: HD1 
00:03:25 Audio program 0: public, type: None, sound experience 0
00:03:25 Slogan: HD1 
00:03:25 Country: US, FCC facility ID: 21
00:03:25 Audio program 0: public, type: None, sound experience 0
00:03:25 Audio program 1: public, type: None, sound experience 0
00:03:25 Country: US, FCC facility ID: 21
00:03:25 Station location: 33.339844, -112.062500, 848m
00:03:25 Audio program 0: public, type: None, sound experience 0
00:03:25 Audio program 1: public, type: None, sound experience 0
00:03:25 Slogan: HD1 
00:03:26 MER: 10.7 dB (lower), 7.5 dB (upper)
00:03:26 BER: 0.000005, avg: 0.000005, min: 0.000005, max: 0.000005
00:03:26 Title: Come On Eileen
00:03:26 Artist: Dexy's Midnight Runners
00:03:26 XHDR: 0 BE4B7536 602
00:03:28 MER: 10.9 dB (lower), 10.9 dB (upper)
00:03:28 BER: 0.000005, avg: 0.000005, min: 0.000005, max: 0.000005
00:03:28 Artist: Dexy's Midnight Runners
00:03:28 Title: Come On Eileen
00:03:28 XHDR: 0 BE4B7536 602
00:03:28 Audio bit rate: 91.6 kbps
00:03:29 MER: 10.8 dB (lower), 10.9 dB (upper)
00:03:29 BER: 0.000003, avg: 0.000005, min: 0.000003, max: 0.000005
00:03:29 SIG Service: type=audio number=1 name=HD1 
00:03:29   Audio component: id=0 port=0000 type=0 mime=4DC66C5A
00:03:29   Data component: id=1 port=1000 service_data_type=265 type=3 mime=BE4B7536
00:03:29   Data component: id=2 port=1001 service_data_type=265 type=3 mime=D9C72536
00:03:29 SIG Service: type=audio number=2 name=HD2
00:03:29   Audio component: id=0 port=0001 type=0 mime=4DC66C5A
00:03:29   Data component: id=1 port=1002 service_data_type=265 type=3 mime=BE4B7536
00:03:29   Data component: id=2 port=1003 service_data_type=265 type=3 mime=D9C72536
00:03:29 Title: Come On Eileen
00:03:29 Artist: Dexy's Midnight Runners
00:03:29 XHDR: 0 BE4B7536 602
00:03:29 Audio bit rate: 91.9 kbps
00:03:30 Audio program 1: public, type: None, sound experience 0
00:03:30 Country: US, FCC facility ID: 21
00:03:30 Slogan: HD1 
00:03:30 Message: HD Radio...www.HD-Radio.com
00:03:30 Station location: 33.339844, -112.062500, 848m
00:03:30 Audio program 0: public, type: None, sound experience 0
00:03:31 MER: 10.6 dB (lower), 10.6 dB (upper)
00:03:31 BER: 0.000003, avg: 0.000004, min: 0.000003, max: 0.000005
00:03:31 Artist: Dexy's Midnight Runners
00:03:31 Title: Come On Eileen
00:03:31 XHDR: 0 BE4B7536 602
00:03:31 Audio bit rate: 91.0 kbps
00:03:32 MER: 10.7 dB (lower), 10.8 dB (upper)
00:03:32 BER: 0.000005, avg: 0.000004, min: 0.000003, max: 0.000005
00:03:32 Title: Come On Eileen
00:03:32 Title: Come On Eileen
00:03:32 Artist: Dexy's Midnight Runners
00:03:32 XHDR: 0 BE4B7536 602
00:03:32 XHDR: 0 BE4B7536 602
00:03:32 Artist: Dexy's Midnight Runners
00:03:32 Audio bit rate: 91.1 kbps
00:03:32 Audio output timed out, dropping samples
00:03:34 MER: 10.7 dB (lower), 10.8 dB (upper)
00:03:34 BER: 0.000005, avg: 0.000005, min: 0.000003, max: 0.000005
00:03:34 Artist: Dexy's Midnight Runners
00:03:34 Title: Come On Eileen
00:03:34 XHDR: 0 BE4B7536 602
00:03:34 Audio bit rate: 90.9 kbps
00:03:35 MER: 10.9 dB (lower), 10.8 dB (upper)
00:03:35 BER: 0.000000, avg: 0.000004, min: 0.000000, max: 0.000005
00:03:35 Artist: Dexy's Midnight Runners
00:03:35 Title: Come On Eileen
00:03:35 XHDR: 0 BE4B7536 602
00:03:35 Audio bit rate: 91.8 kbps
00:03:37 MER: 10.7 dB (lower), 10.9 dB (upper)
00:03:37 BER: 0.000000, avg: 0.000003, min: 0.000000, max: 0.000005
00:03:37 Title: Come On Eileen
00:03:37 Artist: Dexy's Midnight Runners
00:03:37 XHDR: 0 BE4B7536 602
00:03:37 Title: Come On Eileen
00:03:37 Artist: Dexy's Midnight Runners
00:03:37 XHDR: 0 BE4B7536 602
00:03:37 Audio bit rate: 90.8 kbps
00:03:38 MER: 10.7 dB (lower), 10.8 dB (upper)
00:03:38 BER: 0.000000, avg: 0.000003, min: 0.000000, max: 0.000005
00:03:38 Artist: Dexy's Midnight Runners
00:03:38 Title: Come On Eileen
00:03:38 XHDR: 0 BE4B7536 602
00:03:38 Audio bit rate: 91.3 kbps
00:03:38 Audio output timed out, dropping samples
00:03:40 MER: 10.2 dB (lower), 10.2 dB (upper)
00:03:40 BER: 0.000036, avg: 0.000006, min: 0.000000, max: 0.000036
00:03:40 Artist: Lynyrd Skynyrd
00:03:40 Title: Sweet Home Alabama
00:03:40 XHDR: 0 BE4B7536 604
00:03:40 Audio bit rate: 91.3 kbps
00:03:41 MER: 11.0 dB (lower), 11.2 dB (upper)
00:03:41 BER: 0.000000, avg: 0.000006, min: 0.000000, max: 0.000036
00:03:41 Title: Sweet Home Alabama
00:03:41 Artist: Lynyrd Skynyrd
00:03:41 XHDR: 0 BE4B7536 604
00:03:41 Audio bit rate: 91.3 kbps
00:03:43 MER: 11.1 dB (lower), 11.2 dB (upper)
00:03:43 BER: 0.000000, avg: 0.000005, min: 0.000000, max: 0.000036
00:03:43 Title: Sweet Home Alabama
00:03:43 Title: Sweet Home Alabama
00:03:43 XHDR: 0 BE4B7536 604
00:03:43 Artist: Lynyrd Skynyrd
00:03:43 Artist: Lynyrd Skynyrd
00:03:43 XHDR: 0 BE4B7536 604
00:03:43 Audio bit rate: 91.3 kbps
00:03:44 MER: 11.0 dB (lower), 11.1 dB (upper)
00:03:44 BER: 0.000000, avg: 0.000005, min: 0.000000, max: 0.000036
00:03:44 Artist: Lynyrd Skynyrd
00:03:44 Title: Sweet Home Alabama
00:03:44 Audio bit rate: 91.6 kbps
00:03:44 XHDR: 0 BE4B7536 604
00:03:44 Audio output timed out, dropping samples
00:03:45 MER: 11.0 dB (lower), 11.0 dB (upper)
00:03:46 BER: 0.000000, avg: 0.000004, min: 0.000000, max: 0.000036
00:03:46 Artist: Lynyrd Skynyrd
00:03:46 Title: Sweet Home Alabama
00:03:46 XHDR: 0 BE4B7536 604
00:03:46 Audio bit rate: 91.0 kbps
00:03:47 MER: 10.9 dB (lower), 11.1 dB (upper)
00:03:47 BER: 0.000000, avg: 0.000004, min: 0.000000, max: 0.000036
00:03:47 Title: Sweet Home Alabama
00:03:47 Artist: Lynyrd Skynyrd
00:03:47 Artist: Lynyrd Skynyrd
00:03:47 XHDR: 0 BE4B7536 604
00:03:47 Title: Sweet Home Alabama
00:03:47 XHDR: 0 BE4B7536 604
00:03:47 Audio bit rate: 92.0 kbps
00:03:48 MER: 10.8 dB (lower), 11.0 dB (upper)
00:03:49 BER: 0.000000, avg: 0.000004, min: 0.000000, max: 0.000036
00:03:49 Artist: Lynyrd Skynyrd
00:03:49 Title: Sweet Home Alabama
00:03:49 XHDR: 0 BE4B7536 604
00:03:49 Audio bit rate: 91.3 kbps
00:03:49 Audio output timed out, dropping samples
00:03:50 MER: 10.8 dB (lower), 10.8 dB (upper)
00:03:50 BER: 0.000003, avg: 0.000004, min: 0.000000, max: 0.000036
00:03:50 Title: Sweet Home Alabama
00:03:50 Artist: Lynyrd Skynyrd
00:03:50 XHDR: 0 BE4B7536 604
00:03:50 Audio bit rate: 90.6 kbps
00:03:51 MER: 10.9 dB (lower), 10.9 dB (upper)
00:03:51 BER: 0.000000, avg: 0.000004, min: 0.000000, max: 0.000036
00:03:51 Title: Sweet Home Alabama
00:03:51 Artist: Lynyrd Skynyrd
00:03:51 XHDR: 0 BE4B7536 604
00:03:51 Title: Sweet Home Alabama
00:03:51 Artist: Lynyrd Skynyrd
00:03:51 XHDR: 0 BE4B7536 604
00:03:51 Audio bit rate: 91.5 kbps

**Comment by evuraan** [comment]
updated build merged in https://github.com/evuraan/yellowShoes/pull/15
