### ISSUE TITLE
A few feature requests

### ISSUE THREAD

**Issue by cr08** [evuraan/yellowShoes#3]
Came across this project which is just about perfect as a solution for something I've been looking into for a while (ie: Streaming HD Radio in a somewhat automated fashion from an RTL-SDR dongle). A few potential feature requests:

1) The option to allow a server side unified configuration/bookmarks/etc..  - Right now I move between a few different clients and it is a chore to keep bookmarks managed as a single user scenario.
2) Allow manual entry of bookmarks without needing to have them tuned beforehand. Maybe this could be tied into the server side config above and a user editable file on the server?
3) Dynamically update the page title with the current station name and artist/title info? Primary use for me is via Bluetooth in my car and Android provides song data based on the browser tab title it seems like which just says 'yellowShoes' right now.

Maybe a small quirk/bug to be aware of: If joining an in progress session from a second device, it seems to start from the beginning of wherever the wav/mp3 file began and not the current position. Not sure how easily this can be rectified.

**Comment by evuraan** [comment]
@cr08, thank you, those are good suggestions!

Dynamic title (3) was a low hanging fruit, please give branch `dynamicTitle` a try and let me know feedback, if any: https://github.com/evuraan/yellowShoes/tree/dynamicTitle 

0d66bbbff3da18445ffeb416af150b605e8c6c6a

Happy Holidays! 

![image](https://user-images.githubusercontent.com/39205936/147440902-13a3331b-45ae-4433-bdf9-efc3159e0128.png)

**Comment by evuraan** [comment]
ff603e0af96fc0aefd997f5db343528339d49ba0 -  manual entry of bookmarks has been added.

**Comment by evuraan** [comment]
@cr08 , Give https://github.com/evuraan/yellowShoes/tree/importExport a try. All the features you have requested have been added. 


![image](https://user-images.githubusercontent.com/39205936/147627677-542be341-afc3-41da-8c71-e971c7227691.png)

**Comment by evuraan** [comment]
Features added.
