### ISSUE TITLE
output format error

### ISSUE THREAD

**Issue by guywire** [evuraan/yellowShoes#4]
yellowShoes
nrsc5 radio player (HD FM Radio)
Error: Playback failed on 105.1 MHz.
Here's your full log:

21:11:14 INFO  main.c:192: [0] Generic RTL2832U OEM
21:11:14 FATAL main.c:235: Must specify an output format.

in the command line it shows this: cmd nrsc5 105.1 0 -o C:\Users\gampg\AppData\Local\Temp/7J09RlZskUCjsPQF.wav terminated: exit status 1

nrsc5 105.1 0 works fine on the command line and plays audio

**Comment by evuraan** [comment]
Looks like you are using Windows, can you try to run `nrsc5.exe`  at 105.1 0 to save the .wav file and report back the syntax that works for you?

**Comment by guywire** [comment]
I'm not sure how to run yellowshoes in debug mode. Looking for which command line option to use I also noticed that specifying any path folder with -t gives the error "invalid usage"

nrsc5 105.1 0 -o test.wav produces a wav file.

I'd guess the issue is the forward slash in the filepath right before the filename instead of a backslash.

**Comment by evuraan** [comment]
@guywire - updated. please try and let me know.
