### ISSUE TITLE
Unable to set streaming format on iPhone

### ISSUE THREAD

**Issue by taylorwmj** [evuraan/yellowShoes#5]
Changing the streaming format from `.wav` to `.mp3` is not possible on iPhone. There are no options presented on screen, even when zooming out. It is possible to change these settings on iPad, so not an all-encompassing iOS issue. 

Only way to presently change to make work on iPhone is to import settings via Lace Key.

**Comment by evuraan** [comment]
updated, pls try and let me know.

![image](https://user-images.githubusercontent.com/39205936/151914227-f48b3d71-0d19-462b-99fa-381c3f9962e1.png)
