### ISSUE TITLE
Streaming compressed audio - wild goose chase?

### ISSUE THREAD

**Issue by salamanders** [evuraan/yellowShoes#6]
I was pondering about streaming or time shifting compressed audio.  

A: Sounds possible but likely a bad idea: converting from signal to wav to ogg real-time.  Lots of cpu. Re-compresses. Not great. 

B: Sounds super hard: somehow "fix" the not-quite-aac steam enough that most players can handle it. 

B sounds very difficult. Ever heard rumor of someone trying?

**Comment by evuraan** [comment]
wav and mp3 are currently supported, I've no plans to add other formats at this time.
