### ISSUE TITLE
Feature request?

### ISSUE THREAD

**Issue by wryandginger** [evuraan/yellowShoes#7]
First, I love this program. Thank you for all of your work on this! 

I know this is a lot to ask, but is it possible to have yellowShoes download the album art (and the iheartradio maps)?  I know nrsc5-dui and HDFM do this, but I love that I can access this via browser on any device. 

Thanks again! yellowShoes really is the easiest of all the nrsc5 tuners to use.

**Comment by evuraan** [comment]
Thanks for your request, `yellowShoes 5.x` now supports Album Art!

Please try an appropriate build from https://github.com/evuraan/yellowShoes/tree/Album_Art/bin.

Please see the work branch https://github.com/evuraan/yellowShoes/tree/Album_Art fore more details.

![image](https://user-images.githubusercontent.com/39205936/184543864-50c376c2-e82b-4ab5-abe2-1075444643e9.png)

**Comment by wryandginger** [comment]
Wow thanks for this! I've been testing the armv7l build on my octopi server for a bit this afternoon. I definitely got a few inappropriate images lol

Is it possible to just use the --dump-aas-files option when calling nrsc5 and just displaying whatever the station sends? This would hopefully get rid of the network traffic concern, since you wouldn't need to do a search and there'd be no dirty images either.

Thanks again for the super fast update, I really appreciate it.

**Comment by evuraan** [comment]
Thank you! 

Unfortunately `--dump-aas-files` around here is silent on most stations.. I've tried to improve the image tone a little bit - this topic is a [rabbit hole](https://github.com/evuraan/yellowShoes/blob/Album_Art/Screenshots/YellowShoes_EnableAlbumArt.png)!

**Comment by wryandginger** [comment]
Oh okay, I thought you lived in the Seattle area because of your demo stations. 

I'm just south in Tacoma, 106.1 and 96.5 are both iheartradio stations that for sure give album art and traffic data on the --dump-aas-files when I run nrsc5 from the command line. Totally get that this is a bit of a rabbit hole. Thanks again for all of your work on this.

**Comment by cr08** [comment]
Just discovered this request and love the feature add so far. I, too, wouldn't mind seeing the ability to direct pull album art from the HD feed. If it's down to needing sample IQ data to test with, I'd definitely be willing to supply some. We have a good number of stations around here that feed album art and station logos.
