### ISSUE TITLE
IOS + Safari: Unable to import bookmarks or change frequency

### ISSUE THREAD

**Issue by wryandginger** [evuraan/yellowShoes#8]
I'm currently using the most recent version yellowShoes with my iPhone and it recently updated to iOS 16. 

Since the iOS update, I can't import any bookmarks (I enter the correct code and it says 20 items imported, but when I go to the bookmarks none are present.)

Since before this update I also haven't been able to get the frequency slider or the text box to manually tune to a frequency. For example, if I type 94.1 in the input box, but only 88.5 plays. I've tried this on Chrome and Safari on iOS 16 with the same result.

Is there a way to make bookmarks persistent like in your demo instance? Thanks! I do appreciate your work on this.

**Comment by evuraan** [comment]
(This is related to IOS issue https://developer.apple.com/forums/thread/715380 and  https://bugs.webkit.org/show_bug.cgi?id=245479)

Until then, doesn't import work on non-safari browser on your IOS/apple device?

**Comment by wryandginger** [comment]
I’ve tried it on the Chrome and Brave browsers and have the same result. It shows it successfully imports bookmarks but none appear.

**Comment by evuraan** [comment]
Sorry to hear. They may be quite near with the IOS fix - until then, I can try to get you a one-off build - iirc, you need the `armv7l` build, yeah?

Edit: can you please try firefox too?

**Comment by evuraan** [comment]
They are still at it: https://github.com/WebKit/WebKit/pull/6597 

(until they fix Safari, we'd need to use other browsers on IOS16 devices)

**Comment by wryandginger** [comment]
I was hoping that there'd be a fix by ios 16.1.2, but I guess not. Thanks for looking into this.
If you wouldn't mind, I'd love a one-off build for armv7l

Thanks again

**Comment by evuraan** [comment]
How the turns have tabled!  

Safari is the new Internet Explorer and Apple has been just lousy in addressing this bug!

**Comment by evuraan** [comment]
> If you wouldn't mind, I'd love a one-off build for armv7l

See if the band-aid-build in this zip file works for you:

<pre>
$ ls -ltr
total 17112
-rwxrwxr-x 1 nobody nogroup 10478384 Feb  5 10:13 ios_bandaid_build_linux-armv7l
-rw-rw-r-- 1 nobody nogroup  7038425 Feb  5 10:15 bandaid.zip

$ md5sum * 
09932d57930215045f99abaa05a71917  bandaid.zip
a8a78617a5ea3e97a6d82d1b1b1d1a18  ios_bandaid_build_linux-armv7l

$ unzip -l bandaid.zip 
Archive:  bandaid.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 10478384  2023-02-05 10:13   ios_bandaid_build_linux-armv7l
---------                     -------
 10478384                     1 file
</pre> 
[bandaid.zip](https://github.com/evuraan/yellowShoes/files/10611807/bandaid.zip)

**Comment by wryandginger** [comment]
Doesn't seem to make a difference on my end. I still end up with 88.5

**Comment by wryandginger** [comment]
If I make bookmarks on my desktop pc and then export/import settings, I do get working bookmarks on my iphone. That totally is workable for me. (I just wish I could make a persistent lace file.)

**Comment by evuraan** [comment]
This is as IOS/Apple issue - closing. 

I may update this thread if I get a "special" build for IOS, if time allows - but this is not an yellowShoes bug, but an Apple issue. 

Edit: 
2023-04-16 - Apple finally fixed it! `iOS 16.4.1` seems to address this issue.

**Comment by evuraan** [comment]
Apple finally fixed it! iOS 16.4.1 seems to address this issue.
