### ISSUE TITLE
Nginx Revers Proxy redirecting to /main instead of /hdfm/main

### ISSUE THREAD

**Issue by cr08** [evuraan/yellowShoes#9]
Trying to get a reverse proxy config set up through NginxReverseProxy. The config it set up by default is really close to the parameters listed in the README. This is what I'm working with:

````
location /hdfm {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_set_header X-Real-IP		$remote_addr;
    proxy_pass       http://192.168.1.43:8113;
   #proxy_pass http://192.168.1.43:8113/main;
    
    # Force SSL
    include conf.d/include/force-ssl.conf;

  # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
  add_header Strict-Transport-Security "max-age=63072000;includeSubDomains; preload" always;

    proxy_set_header X-Forwarded-Host $host:$server_port;
proxy_set_header X-Forwarded-Server $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
````

So it should be accessible at https://mydomain.com/hdfm/main, however when going here it keeps redirecting back to https://mydomain.com/main/main.

I know on some other applications they specifically need to be made aware they are running via a subfolder through some equivalent of a 'baseurl' variable. Not sure if that is what's needed here or maybe I'm missing something? The example in the README is based on Apache instead of Nginx and I'm not terribly familiar with the former these days (I think the last time I messed with Apache was a solid 15-20 years ago).

I'm going to continue playing with this in the meantime to see if I can resolve it.

**Comment by cr08** [comment]
Fixed! Apparently needed to add some trailing slashes which NginxProxyManager missed. Had to go in and manually tweak the config files.

````
location /hdfm/ {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_set_header X-Real-IP		$remote_addr;
    proxy_pass       http://192.168.1.43:8113/;
````

This got it going. To clarify, a trailing slash is required on both the location directive `/hdfm/` as well as the prox_pass directive.

**Comment by cr08** [comment]
Reopening this as I've come back to play with this a bit more. Seems like running behind a reverse proxy with an SSL cert breaks it in a weird way. I can access it and tune a station but it acts like the tuning stage failed. Times out and shows the log on screen. But the log shows the tuning stage went fine and I can guarantee the station I've tested with has a strong signal here. Accessing YellowShoes direct via IP (haven't had a chance to set up a reverse proxy on a domain/subdomain without SSL yet to test) it behaves fine.

**Comment by evuraan** [comment]
@cr08, not saying it works for me, but please take some time and investigate this on your end. I do use my instance behind apache as a TLS [reverse proxy](https://github.com/evuraan/yellowShoes#routingproxying) and had not have issues with it. Case in point, the [public facing demo instance ](https://evuraan.info/yellowShoesDemo/main). Your usb dongle may take longer to tune, even with a stronger signal. Another option, please try setting a larger `playerTimeout` as in https://github.com/evuraan/yellowShoes/issues/2.
